### ISSUE TITLE
Bulk load already existing graph?

### ISSUE THREAD

**Issue by DavidTou** [RedisGraph/redisgraph-bulk-loader#102]
Is there anyway to Bulk Load into already existing graph?

**Comment by DavidTou** [comment]
BULk load spec describes the following: https://redis.io/docs/stack/graph/design/bulk_spec/

`The endpoint cannot be used to update existing graphs, only to create new ones. For this reason, the first query in a sequence of BULK commands should pass the string literal "BEGIN".`

**Comment by swilly22** [comment]
@DavidTou you might want to look at the bulk update functionality
