### ISSUE TITLE
Asynchronously Process bulk loads

### ISSUE THREAD

**Issue by Dsolnik** [RedisGraph/redisgraph-bulk-loader#51]
Currently, bulk loads run on the Redis Main thread.

Maybe this can be done asynchronously?

Suggested here:
https://forum.redislabs.com/t/bulk-loader-locking-application/995

**Comment by jeffreylovitz** [comment]
This has been added to RedisGraph with the PR https://github.com/RedisGraph/RedisGraph/pull/1596 .
