### ISSUE TITLE
Pip package no longer exposes `redisgraph-bulk-loader`

### ISSUE THREAD

**Issue by szarnyasg** [RedisGraph/redisgraph-bulk-loader#67]
The latest package installed from pip no longer exposes `redisgraph-bulk-loader`, instead, it has `redisgraph-bulk-insert` and `redisgraph-bulk-update`:

```bash
root@1bb2cd4ab07a:/# pip install redisgraph-bulk-loader
...
root@1bb2cd4ab07a:/# redisgraph-bulk-<TAB>
redisgraph-bulk-insert  redisgraph-bulk-update  
```

**Comment by jeffreylovitz** [comment]
@szarnyasg You are correct, in the latest version we switched build environments and inadvertently renamed `redisgraph-bulk-loader` to `redisgraph-bulk-insert`.

This is an unintended breaking change, but at the same time I feel that the new name is more appropriate, so I am unsure whether it should be reverted. What do you think?

**Comment by szarnyasg** [comment]
@jeffreylovitz I'm fine with the change. My only recommendation then would be to reflect this change in the README of this repository.

**Comment by jeffreylovitz** [comment]
I agree; I will update the documentation and the release notes to reflect this.

**Comment by jeffreylovitz** [comment]
All the relevant documentation has been updated to reflect the new entrypoint, so I am closing this issue.

Thanks for the report, @szarnyasg!
