### ISSUE TITLE
Question: Attributes to contain ":" Character

### ISSUE THREAD

**Issue by YaphetKG** [RedisGraph/redisgraph-bulk-loader#71]
If we had a dataset such as :

```
subject:STRINGpredicate:STRINGobject:STRINGrelation:STRINGinternal_start_id:START_IDinternal_end_id:END_IDid:IDbiolink:aggregator_knowledge_source:STRING 
abiolink:biomarker_forbRO:0002607abedge-idsomeprovider
```
If we notice the last attribute name  
`biolink:aggregator_knowledge_source` it contains `:` which causes some confusion on the bulk loader , but it would be nice if there had some way of supporting these kinds of attribute names.

**Comment by jeffreylovitz** [comment]
Hi @YaphetKG,

Your example header is a bit confusing, as it only has schema data types for some of the fields.

You are correct that running the bulk loader with `--enforce-schema` doesn't currently allow property names to contain colons, though. This can be easily rectified by just seeking the last colon to find schema information. Would that be preferable to you?

Note that when querying your data, you'll need to backtick-escape the property key to avoid syntax errors:
```
MATCH (a) RETURN a.`biolink:biomarker_for`
```

**Comment by YaphetKG** [comment]
hi @jeffreylovitz , thanks for the quick response, yes I think that would work for us too.  and thanks for the hint , we have our queries all backtick'ed
